name: Deploy IsItAPie to isitapie.com

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
        
      - name: Build site
        run: npm run build

      - name: SCP Files
        uses: appleboy/scp-action@master
        with:
          host: thegreatescapism.com
          username: github
          source: /home/runner/work/is-it-a-pie/is-it-a-pie/dist/*
          target: /var/www/is-it-a-pie/root
          tar_tmp_path: /home/github/temp
          strip_components: 3
          rm: true
          key: ${{ secrets.SSH_PRIVATE_KEY }}
